# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaSistema.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(619, 314)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(510, 170, 101, 41))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.marcarDesconto = QtWidgets.QRadioButton(self.groupBox)
        self.marcarDesconto.setGeometry(QtCore.QRect(0, 0, 82, 17))
        self.marcarDesconto.setObjectName("marcarDesconto")
        self.marcarAcrescimo = QtWidgets.QRadioButton(self.groupBox)
        self.marcarAcrescimo.setGeometry(QtCore.QRect(0, 20, 91, 17))
        self.marcarAcrescimo.setObjectName("marcarAcrescimo")
        self.botaoAplicar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoAplicar.setGeometry(QtCore.QRect(150, 240, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.botaoAplicar.setFont(font)
        self.botaoAplicar.setObjectName("botaoAplicar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 160, 41, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.entradaValorAtual = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaValorAtual.setGeometry(QtCore.QRect(340, 10, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.entradaValorAtual.setFont(font)
        self.entradaValorAtual.setObjectName("entradaValorAtual")
        self.entradaValorObjetivo = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaValorObjetivo.setGeometry(QtCore.QRect(340, 90, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.entradaValorObjetivo.setFont(font)
        self.entradaValorObjetivo.setObjectName("entradaValorObjetivo")
        self.entradaPorcentagem = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaPorcentagem.setGeometry(QtCore.QRect(340, 160, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.entradaPorcentagem.setFont(font)
        self.entradaPorcentagem.setObjectName("entradaPorcentagem")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 2, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Frinex Porcentagens"))
        self.marcarDesconto.setText(_translate("MainWindow", "Desconto"))
        self.marcarAcrescimo.setText(_translate("MainWindow", "Acrescimo"))
        self.botaoAplicar.setText(_translate("MainWindow", "APLICAR"))
        self.label_4.setText(_translate("MainWindow", "%"))
        self.label_3.setText(_translate("MainWindow", "VALOR OBJETIVO"))
        self.label.setText(_translate("MainWindow", "VALOR ATUAL"))
        self.label_2.setText(_translate("MainWindow", "PORCENTAGEM"))
